language: node_js
before_script:
- npm install
script: npm test
deploy:
  provider: heroku
  app: me-boaviagem-api
  api_key:
    secure: D5Gu3G57igZVmuuS9iTVfIqdl26bmRMWWWV9wmuX/AEUToMf/8gK8UDeciaMu+SRODefkYRdOvRFoGHPXdVnNxC1EegSUBC2Rt+kncoh69XL6NdO1WpCCBcOBT1GgYk3a9iBrjYPrLwkVD0n57MFEKs15WwXy2jAi2Z0L9oRFhsvtpCo+9Aa5PyYomn58IrZip6jt1p6/oVRapVo1C5kCBVhevBV37a5OQ00zay+tCiv/+1q5jeyfqsIBkh3H0DIOxi8VuvQOoYIdnyjNxmwoJWOI8stXC1lEgL/MideTDSpmQjJ9mDA4x/gxaiaCOPO1HHuAAT/QFB7G7xM7FAV0W9BKGxO0sa1UJP2e+qDE0a/F7CrV3h8NkStc2AuIge07CSgPs+Vz52mGYvoE/xc23q5FFJ/j0GoIiQZmC3P0DpdswijZZR0za4/lbcQ+Ifteg7NV6LTOvOzpVtb9hd1Dfz1jkhoZ0hhLloOcqAbowS8/Y8m9tV7dpv+4R5TlNdRU7agc/oRYbKBmRCCJ9ezO3h7uNUgqwVa0r/L0Elbb+FjqKbDXKcWihH3WPk3PInUK8I1U/CYxNoSjW5pYNE/lZvN+xjeB474ixvHG0jQp0SiQRZHpzovVpPl8YrJPSifYJX1xmHr/KuMw8QCqfQo0lgIY5m+9ri65KT15oOXRhw=
  on:
    repo: giovanebribeiro/me.boaviagem.api
